apiVersion: v1
kind: Secret
metadata:
  name: inventro-django-secret
  namespace: inventro
type: Opaque
stringData:
  DJANGO_SECRET_KEY:
  DJANGO_SUPERUSER_USERNAME:
  DJANGO_SUPERUSER_EMAIL:
  DJANGO_SUPERUSER_PASSWORD: