apiVersion: v1
kind: Secret
metadata:
  name: inventro-do-secret
  namespace: inventro
type: Opaque
stringData:
  # ----------------------------------------------------------------------
  # Object storage (DigitalOcean Spaces / S3) for backups or media
  # ----------------------------------------------------------------------
  DO_SPACES_KEY:
  DO_SPACES_SECRET:
  DO_SPACES_REGION:
  DO_SPACES_BUCKET: