apiVersion: v1
kind: Secret
metadata:
  name: inventro-registry
  namespace: kube-system
  annotations:
    digitalocean.com/dosecret-identifier: inventro-registry
type: kubernetes.io/dockerconfigjson
data:
  # Must be filled with base64 encoded Docker config JSON. 
  # For more information go to https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/#create-a-secret-for-a-private-registry
  .dockerconfigjson:
