apiVersion: v1
kind: ConfigMap
metadata:
  name: inventro-db-config
  namespace: inventro
  
data:
  POSTGRES_DB: "inventro"
  POSTGRES_HOST: "inventro-postgres-service"
  POSTGRES_PORT: "5432"
  POSTGRES_USER: "postgres_user"
  DEBUG: "0"
