apiVersion: v1
kind: ConfigMap
metadata:
  name: inventro-db-config
  namespace: inventro
  
data:
  POSTGRES_DB: example-db-name
  POSTGRES_HOST: example-postgres-host
  POSTGRES_PORT: example-postgres-port
  POSTGRES_USER: example-postgres-user
  DEBUG: "true"
