apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: inventro
data:
  default.conf: |
    server {
        listen 80;

        location / {
            proxy_pass http://inventro-service:8000;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $host;
            proxy_connect_timeout 10s;
            proxy_send_timeout 10s;
            proxy_read_timeout 10s;

        }

        location /static/ {
            alias /staticfiles/;
            proxy_connect_timeout 10s;
            proxy_send_timeout 10s;
            proxy_read_timeout 10s;

        }
    }
