apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgres-backup
  namespace: inventro
spec:
  schedule: "0 2 * * *" # daily at 02:00 UTC
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: backup
              image: python:3.11-alpine
              env:
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: inventro-postgres-secret
                      key: POSTGRES_PASSWORD
              envFrom:
                - configMapRef:
                    name: inventro-db-config
                - secretRef:
                    name: inventro-postgres-secret
                - secretRef:
                    name: inventro-django-secret
                - secretRef:
                    name: inventro-do-secret
              command:
                - /bin/sh
                - -c
                - |
                  set -e
                  echo "Installing dependencies..."
                  apk add --no-cache postgresql-client curl bash openssl ca-certificates
                  # install mc (MinIO client)
                  curl https://dl.min.io/client/mc/release/linux-amd64/mc -O
                  chmod +x mc
                  TIMESTAMP=$(date +%F_%H%M%S)
                  FNAME="/tmp/backup-${TIMESTAMP}.sql"
                  echo "Dumping DB to ${FNAME}..."
                  pg_dump -h "$POSTGRES_HOST" -U "$POSTGRES_USER" -d "$POSTGRES_DB" -F p > "$FNAME"
                  echo "$DO_SPACES_KEY"
                  echo "Configuring mc for Spaces..."
                  ./mc alias set dok8s "https://$DO_SPACES_REGION.digitaloceanspaces.com" "$DO_SPACES_KEY" "$DO_SPACES_SECRET"
                  echo "Uploading ${FNAME} to Spaces bucket ${DO_SPACES_BUCKET}..."
                  ./mc cp "$FNAME" dok8s/"$DO_SPACES_BUCKET"/backup-"$TIMESTAMP".sql
                  echo "Backup done."
          restartPolicy: OnFailure
