apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: inventro-ingress
  namespace: inventro
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: inventro.terryluan.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: inventro-service
            port:
              number: 80
