apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: inventro
resources:
  - namespace.yaml
  - secret.yaml
  - configmap.yaml
  - postgres-statefulset.yaml
  - django-deployment.yaml
  - hpa.yaml
