apiVersion: v1
kind: Secret
metadata:
  name: inventro-secrets
  namespace: inventro
type: Opaque
data:
  SECRET_KEY: ZGV2LXN1cGVyLXNlY3JldC1jaGFuZ2UtbWU=   # base64
  POSTGRES_PASSWORD: c3VwZXJzZWNyZXRwYXNz            # base64
