apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventro-postgres-deployment
  namespace: inventro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventro-postgres
  template:
    metadata:
      labels:
        app: inventro-postgres
    spec:
      containers:
        - name: postgres-pvc
          image: postgres:15
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready -d "$POSTGRES_DB" -U "$POSTGRES_USER"
            initialDelaySeconds: 5
            periodSeconds: 5
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: inventro-postgres-secret
                  key: POSTGRES_PASSWORD
          envFrom:
            - configMapRef:
                name: inventro-db-config
          
          resources:
            requests:
              cpu: "50m"
              memory: "256Mi"
            limits:
              cpu: "100m"
              memory: "512Mi"
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-data
              subPath: data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc