apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventro-deployment
  namespace: inventro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventro-web
  template:
    metadata:
      labels:
        app: inventro-web
    spec:
      initContainers:
      - name: wait-for-postgres
        image: curlimages/curl:latest
        args:
        - /bin/sh
        - -c
        - >
          set -x;
          while ! nc -z inventro-postgres-service 5432; do
            sleep 15;
          done
      containers:
        - name: inventro-web
          image: registry.digitalocean.com/inventro-registry/inventro-web:latest
          imagePullPolicy: Always
          command: ["./entrypoint.sh"]
          ports:
            - containerPort: 8000
          env:
            - name: GUNICORN_CMD_ARGS
              value: "--access-logfile - --error-logfile -"
            - name: POPULATE_DATABASE
              value: "0"
          envFrom:
            - configMapRef:
                name: inventro-db-config
            - secretRef:
                name: inventro-url-secret
            - secretRef:
                name: inventro-django-secret
            - secretRef:
                name: inventro-postgres-secret
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "200m"
              memory: "512Mi"

  # Uncomment the following lines if using a private container registry
  # imagePullSecrets:
  #   - name: inventro-registry