apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: inventro
spec:
  type: LoadBalancer
  selector:
    app: inventro-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80