apiVersion: v1
kind: Service
metadata:
  name: inventro-postgres-service
  namespace: inventro
spec:
  type: ClusterIP
  selector:
    app: inventro-postgres
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
