apiVersion: v1
kind: Service
metadata:
  name: inventro-service
  namespace: inventro
spec:
  type: ClusterIP
  selector:
    app: inventro-web
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
